name: 'clean_repo'

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:

permissions:
  #contents: read
  contents: write

jobs:
  cleanrepo:
    name: 'Terraform'
    runs-on: mosc01
    #environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Commit changes
      run: |
        git config --global user.email "omarinux@gmail.com"
        git config --global user.name "GitHub Actions"
        rm -rf .terraform* && rm -rf test02.txt && 
        echo `git add -A && git commit -m "Update Terraform tfstate"`
        #git add terraform.tfstate
        #git commit -m "Update Terraform tfstete"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
